name: Build and Publish Package

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: dottie
          #
          # - name: macos-aarch64
          #   os: macos-latest
          #   target: aarch64-apple-darwin # for Arm based macs (M1 and above).
          #   binary: dottie
          #
          # - name: macos-x86_64
          #   os: macos-latest
          #   target: x86_64-apple-darwin # for Intel based macs.
          #   binary: dottie
          #
          # - name: windows-x86_64
          #   os: windows-latest
          #   target: x86_64-pc-windows-msvc
          #   binary: dottie.exe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dottie-${{ matrix.name }}
          path: target/${{ matrix.target }}/release/${{ matrix.binary }}
          if-no-files-found: error

  release:
    needs: build
    name: Release to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Obtain built version
        working-directory: artifacts/dottie-linux-x86_64
        run: |
          chmod +x ./dottie*
          ./dottie info -v
          echo "DOTTIE_VERSION=$(./dottie info -v)" >> "$GITHUB_ENV"

      - name: Package artifacts
        working-directory: artifacts
        run: |
          for target in *; do
            [ -d "$target" ] || continue
            cd "$target" || continue
            echo -e "\033[44;1m Packaging \033[0m \033[1;4m$target\033[0m"
            chmod +x ./dottie*
            if grep -qE '(macos|windows)' <<<"$target"; then
              zip "../$target-${{ env.DOTTIE_VERSION }}.zip" ./*
            else
              tar czfv "../$target-${{ env.DOTTIE_VERSION }}.tar.gz" ./*
            fi
            cd ..
          done

      - name: Make Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          token: ${{ secrets.TOKEN_SAPLYN_DOTTIE_ACTION }}
          tag_name: ${{ env.DOTTIE_VERSION }}
          files: artifacts/*
